#!/bin/sh
mount -t proc proc /proc
mount -t sysfs sysfs /sys
mount -t devtmpfs dev /dev
mkdir -p /dev/pts
mount -t devpts devpts /dev/pts 2>/dev/null || true
hostname rezzos
echo 0 > /proc/sys/kernel/printk
ifconfig lo 127.0.0.1 up
ifconfig eth0 10.0.2.15 netmask 255.255.255.0 up
route add default gw 10.0.2.2
echo "nameserver 8.8.8.8" > /etc/resolv.conf
mount /dev/vda /mnt/disk 2>/dev/null
clear
/usr/bin/fetch
echo ""
